-- ============================================
-- AI Auto-Response System: Conversations & Messages
-- Run this in your Supabase SQL Editor
-- ============================================

-- Enable UUID generation
create extension if not exists "uuid-ossp";

-- Conversations table
create table conversations (
  id uuid default uuid_generate_v4() primary key,
  client_name text not null,
  client_email text not null,
  budget text,
  status text default 'active' check (status in ('active', 'escalated', 'closed')),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Messages table
create table messages (
  id bigint generated by default as identity primary key,
  conversation_id uuid references conversations(id) on delete cascade not null,
  role text not null check (role in ('client', 'ai', 'human')),
  content text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Index for fast lookups
create index idx_messages_conversation on messages(conversation_id);
create index idx_conversations_email on conversations(client_email);
create index idx_conversations_status on conversations(status);

-- RLS
alter table conversations enable row level security;
alter table messages enable row level security;

-- Allow anon insert (from Cloudflare Functions using anon key)
create policy "Service can insert conversations" on conversations
  for insert with check (true);

create policy "Service can update conversations" on conversations
  for update using (true);

create policy "Service can select conversations" on conversations
  for select using (true);

create policy "Service can insert messages" on messages
  for insert with check (true);

create policy "Service can select messages" on messages
  for select using (true);

-- Auto-update updated_at on conversations
create or replace function update_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

create trigger conversations_updated_at
  before update on conversations
  for each row execute function update_updated_at();
