-- Create a table for public profiles using Supabase Auth ID
create table profiles (
  id uuid references auth.users not null primary key,
  updated_at timestamp with time zone,
  email text,
  full_name text,
  avatar_url text,
  website text,

  constraint username_length check (char_length(username) >= 3)
);

-- Set up Row Level Security (RLS)
alter table profiles enable row level security;

create policy "Public profiles are viewable by everyone." on profiles
  for select using (true);

create policy "Users can insert their own profile." on profiles
  for insert with check (auth.uid() = id);

create policy "Users can update own profile." on profiles
  for update using (auth.uid() = id);

-- Create a generic contacts table for form submissions
create table contacts (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text,
  email text,
  budget text,
  message text
);

-- RLS for contacts (Admin only usually, or public insert)
alter table contacts enable row level security;

-- Allow anyone to insert (Contact Form)
create policy "Anyone can insert contacts" on contacts
  for insert with check (true);

-- Only authenticated admins can view (Optional, assuming you are admin)
-- For simplicity, we allow no one to select publicly (only via dashboard or service role)
-- But wait, frontend doesn't select. Backend function uses service role?
-- Actually, Cloudflare function uses anon key usually. Anon key respects RLS.
-- So we need to allow insert for public (anon).

-- Function to handle new user profile creation automatically
create function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, email, full_name)
  values (new.id, new.email, new.raw_user_meta_data->>'full_name');
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
